# Generated by Django 4.2.1 on 2023-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
