# Generated by Django 4.2.1 on 2023-06-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
