# Generated by Django 4.2.1 on 2023-07-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
