# Generated by Django 4.2.1 on 2023-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_color',
            field=models.TextField(default='Red', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_size',
            field=models.TextField(default='Medium', verbose_name='Size'),
        ),
    ]
