# Generated by Django 4.2.1 on 2023-10-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_cart_product_color_cart_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Size Id'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
