# Generated by Django 3.2.3 on 2023-12-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_size_id_alter_size_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Select a color for the image', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color'),
        ),
    ]
