# Generated by Django 3.2.3 on 2023-12-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Color Id'),
        ),
    ]
